Numbers = int(input('Enter an integer value: '))
print("The double that number is {}".format(Numbers * 2))
print("The triple that number is {}".format(Numbers * 3))
print("The square root that number is {}".format(Numbers ** (1 / 2)))
print(pow(Numbers, 1 / 2))
